[package]
name = "vmspect"
version = "0.3.0"
edition = "2021"
authors = ["Juan"]
description = "Blazing-fast static inspection, forensic analysis and information extraction library for virtual machine disk images (VMDK, RAW, QCOW2, VHD, VHDX, VDI)."
license = "MIT OR Apache-2.0"
readme = "readme.md"
repository = "https://github.com/jcostasuarez/vmspect"
keywords = ["vm", "vmdk", "qemu", "inspection", "forensics"]
categories = ["filesystem", "command-line-utilities", "parser-implementations"]

[dependencies]
thiserror = "1.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
ext4 = "0.9"
ntfs = "0.4"
nt-hive = "0.3"
positioned-io = "0.2"
tracing = "0.1"

[dev-dependencies]
tempfile = "3.10"
